### ISSUE TITLE
<div> in granite-clipboard should not be display: block; by default

### ISSUE THREAD

**Issue by Boscop** [LostInBrittany/granite-clipboard#2]
IMO, the `<div>` inside the `<granite-clipboard>` should not be `display: block;` by default.
Because I want to use it inline with other action buttons.
Right now it only works when I do this:
```css
granite-clipboard, granite-clipboard ::content div {
  display: inline;
}
```
But this seems hacky, I'm not sure if this is a good way to achieve this.

**Comment by LostInBrittany** [comment]
I agree, it feels a bit hacky... 
I'm not sure if there is a better way to do it, `<div>` are  `display: block;` by default...

**Comment by Boscop** [comment]
@LostInBrittany maybe it should be a `<span>` instead, so that it's inline by default.

**Comment by LostInBrittany** [comment]
hmmm, going to test if that would break something, it could be a good solution...

another one is putting that `<div>` as an `inline-block`. Would that work for you?

**Comment by Boscop** [comment]
AFAIK this kind of usecase is exactly what `<span>` is for:
[semantically, divs should be used to wrap sections of a document, while spans should be used to wrap small portions of text, images, etc.](http://stackoverflow.com/a/183536/7488353)

**Comment by LostInBrittany** [comment]
IMO it's not the case. In theory, it's illegal to wrap a block level element in a inline level element, i.e. it's illegal to put a `<div>` inside a `<span>`. Right now the `<div>`  is used to wrap the LightDOM content, i.e. whatever you put inside the `<granite-clipboard>`. It can be an inline thing, in your case, or a block thing, as in some of my cases. So in order to be semantically correct, I need it to be a `<div>` and not a `<span>`.

Not sure if I explained it well...

**Comment by LostInBrittany** [comment]
In fact, I've just tested, and I don't see a problem...

If you want `granite-clipboard` to be `inline`, or `inline-block`, you only need to set it as `inline`, or `inline-block` with CSS, you don't need to touch it's inner `div`, it will follow it's parent.

Example:

```
<style>
      .inlineClipboard {
        display:inline-block;
      }
</style>
<div> 
   Here an inline use case
   <granite-clipboard class="inlineClipboard" text="Text to be copied">
     <div style="width:250px;height:50px;border-radius:5px;background-color: #aaaaff;cursor:pointer;">Hohoho</div>
   </granite-clipboard> 
   does it work?
</div>
```  

And you get: 

![image](https://cloud.githubusercontent.com/assets/726476/23118276/e3a2beaa-f753-11e6-97c8-8334762038dd.png)

I'm putting it as a second example in the demo.

Can you tell me if it answers your question/solves your problem?

**Comment by Boscop** [comment]
For me, if I use this:
```css
granite-clipboard {
  display: inline;
}
```
with this:
```html
    <granite-clipboard text="{$ config.appUrl $}[[url]]">
      <paper-icon-button class="viewer-action" icon="share"
        title="Click to copy link for sharing"
        on-tap="btn_action_copied_link"
      ></paper-icon-button>
    </granite-clipboard>
```
I get this:
![](https://i.imgur.com/QnCfQ6T.png)

I have to use this:
```css
granite-clipboard, granite-clipboard ::content div {
  display: inline;
}
```
to get the desired behavior:
![](https://i.imgur.com/iyHqoa4.png)

**Comment by LostInBrittany** [comment]
Not sure :)

It seems rather similar to the test case I put before. Have you tried with `inline-block` instad of `inline`?

I'm going to try to reproduce and I tell you :)

**Comment by LostInBrittany** [comment]
O.K., I've tested, if using `inline-block` instead of `inline` your problem disappears.

You can put an ` block` item inside an ` inline-block` and it will work ok, but if you put it inside a ` inline` it will display as a block.

Could you please test and tell me if it's ok for you?

**Comment by Boscop** [comment]
Ah thanks, it works!

**Comment by LostInBrittany** [comment]
Glad it worked! And thanks for the issue, that made me think a lot about
that CSS box model... :)
