### ISSUE TITLE
Remove console output

### ISSUE THREAD

**Issue by avdaredevil** [LostInBrittany/granite-clipboard#3]
Awesome wrapper. I had one hiccup with this component, and that is that it prints to the console every time it copies something. Could this perhaps be toggleable via a property or removed? Since the app produces other forms of output, and this just takes importance away from more critical messages being generated. Thanks!

**Comment by LostInBrittany** [comment]
Of course! I had an old habitude of putting logs everywhere, and often I forget how they can be verbose,,, Going to add a `verbose` parameter and log only if `verbose` is set

**Comment by avdaredevil** [comment]
Awesome! Looking forward 👍

**Comment by LostInBrittany** [comment]
Done :)
