### ISSUE TITLE
Copying does not work in modal paper-dialog

### ISSUE THREAD

**Issue by strepon** [LostInBrittany/granite-clipboard#4]
The copying to clipboard works nicely excepting the case of `granite-clipboard` placed into `paper-dialog` with the `modal` attribute. Then, everything seems to be OK (including the console output), but nothing is copied.

This is probably related to zenorocha/clipboard.js#388, but changing tabindex as suggested there does not help.

Could this be workarounded somehow?

**Comment by LostInBrittany** [comment]
Ouch, I had't tested that case, going to test it and try to solve it.

Thanks!
